default_stages: [commit, merge-commit, push, prepare-commit-msg, commit-msg, post-checkout, post-commit, post-merge, post-rewrite]
repos:
-   repo: https://github.com/python/black
    rev: 22.8.0
    hooks:
    -   id: black