version: "3.9"
services:
  # run schematic APIs in a docker container with uWSGI and nginx
  schematic-aws:
    # build: 
    #   context: ../schematic
    #   dockerfile: schematic_api/Dockerfile
    # container_name: schematic-api-aws
    image: thomasvyu/schematic
    entrypoint: python run_app.py
    restart: always
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "3001"
      SCHEMATIC_CONFIG_CONTENT: ${SCHEMATIC_CONFIG_CONTENT}
      SERVICE_ACCOUNT_CREDS: ${SERVICE_ACCOUNT_CREDS}
      GE_HOME: app/great_expectations/
    networks:
      - schematic
    ports: 
      - "3001:3001"
      # - "${USE_LISTEN_PORT}:80"
      # - "443:443"
networks:
  schematic:
    name: schematic