name: trigger-dca

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:  # Allow manually triggering the workflow
concurrency:
  # cancel the current running workflow from the same branch, PR when a new workflow is triggered 
  # when the trigger is not a PR but a push, it will use the commit sha to generate the concurrency group
  # {{ github.workflow }}: the workflow name is used to generate the concurrency group. This allows you to have more than one workflows
  # {{ github.ref_type }}: the type of Git ref object created in the repository. Can be either branch or tag 
  # {{ github.sha }}: full commit sha 
  # credit: https://github.com/Sage-Bionetworks-Workflows/sagetasks/blob/main/.github/workflows/ci.yml
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.sha }}
  cancel-in-progress: true
jobs:
  pypi_release:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       Compute short commit sha
      #----------------------------------------------
      - name: Compute short commit SHA ID
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      #----------------------------------------------
      #       Extract branch name 
      #----------------------------------------------
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Get pushed tag, if any
        run:  |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION }}
  
      #----------------------------------------------
      #       Trigger DCA testing instance   
      #----------------------------------------------
      - name: Trigger DCA testing instance 
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/Sage-Bionetworks/data_curator/dispatches \
          -d '{"event_type": "trigger-frontend", "client_payload": { "branch": "'${{ steps.extract_branch.outputs.branch }}'", "commit-sha": "'${{ steps.vars.outputs.sha_short }}'",  "release-version": "${{ env.RELEASE_VERSION }}"}'

